# ===================================
#  List Behavior Config
# ===================================

title: ovillani.userpermissions::lang.permissions.menu_label
list: ~/plugins/ovillani/userpermissions/models/permission/columns.yaml
modelClass: OVillani\UserPermissions\Models\Permission
recordUrl: ovillani/userpermissions/permissions/update/:id

noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 20

showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
